"""empty message

Revision ID: 073053c20cb5
Revises: 7967a4a45dcc
Create Date: 2023-01-28 17:34:55.181057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073053c20cb5'
down_revision = '7967a4a45dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_pass', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('key_pass')

    # ### end Alembic commands ###
