"""empty message

Revision ID: 146c7fa594da
Revises: a6a5f7ce4a8f
Create Date: 2023-01-14 09:51:35.806862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146c7fa594da'
down_revision = 'a6a5f7ce4a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userEnvio', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('userRecibe', sa.Integer(), nullable=True))
        batch_op.alter_column('mail',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'user', ['userEnvio'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['userRecibe'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('mail',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('userRecibe')
        batch_op.drop_column('userEnvio')

    # ### end Alembic commands ###
