"""empty message

Revision ID: 2b93d0c3b1eb
Revises: 7da3a96191e5
Create Date: 2023-01-26 11:38:52.056858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b93d0c3b1eb'
down_revision = '7da3a96191e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('horas', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('dia', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('mes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('anio', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajos', schema=None) as batch_op:
        batch_op.drop_column('anio')
        batch_op.drop_column('mes')
        batch_op.drop_column('dia')
        batch_op.drop_column('horas')
        batch_op.drop_column('precio')

    # ### end Alembic commands ###
