"""empty message

Revision ID: 97373ea12b37
Revises: 70be2bf216fb
Create Date: 2023-01-19 19:32:29.241446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97373ea12b37'
down_revision = '70be2bf216fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
