"""empty message

Revision ID: ba74cd82b849
Revises: 2b24ea6ea032
Create Date: 2023-01-25 10:40:03.125733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba74cd82b849'
down_revision = '2b24ea6ea032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_list', schema=None) as batch_op:
        batch_op.alter_column('id_profesional',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_list', schema=None) as batch_op:
        batch_op.alter_column('id_profesional',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
