"""empty message

Revision ID: ca0664738e00
Revises: dbe086011a72
Create Date: 2023-01-11 16:10:44.853234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0664738e00'
down_revision = 'dbe086011a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('userprofesional')
        batch_op.drop_column('lastname')
        batch_op.drop_column('name')
        batch_op.drop_column('userclient')
        batch_op.drop_column('zipcode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zipcode', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('userclient', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('userprofesional', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
