"""empty message

Revision ID: dbe086011a72
Revises: 7c48699776b9
Create Date: 2023-01-10 18:54:32.384469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe086011a72'
down_revision = '7c48699776b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=50), nullable=False),
    sa.Column('profession', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('zipcode', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('userprofesional', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('userclient', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('userclient')
        batch_op.drop_column('userprofesional')
        batch_op.drop_column('zipcode')
        batch_op.drop_column('city')
        batch_op.drop_column('lastname')
        batch_op.drop_column('name')

    op.drop_table('announce')
    # ### end Alembic commands ###
