"""empty message

Revision ID: e4c823224a7e
Revises: ba74cd82b849
Create Date: 2023-01-25 10:42:28.484899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c823224a7e'
down_revision = 'ba74cd82b849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_list', schema=None) as batch_op:
        batch_op.alter_column('id_profesional',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_list', schema=None) as batch_op:
        batch_op.alter_column('id_profesional',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
