"""empty message

Revision ID: e587a43f92f5
Revises: dc4b1ea42c01
Create Date: 2023-01-13 12:33:01.686240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e587a43f92f5'
down_revision = 'dc4b1ea42c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=50), nullable=False),
    sa.Column('profession', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('mesagge')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesagge',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mail', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('profession', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='mesagge_pkey')
    )
    op.drop_table('message')
    # ### end Alembic commands ###
