"""empty message

Revision ID: f9ef7f66edb2
Revises: e587a43f92f5
Create Date: 2023-01-14 08:32:15.875144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ef7f66edb2'
down_revision = 'e587a43f92f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=20), nullable=False))
        batch_op.drop_column('profession')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profession', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
